variable "project_name"       { type = string; default = "k8s-platform" }
variable "environment"        { type = string; default = "dev" }
variable "aws_region"         { type = string; default = "ap-southeast-1" }
variable "vpc_cidr"           { type = string; default = "10.0.0.0/16" }
variable "kubernetes_version" { type = string; default = "1.29" }
variable "node_instance_type" { type = string; default = "t3.medium" }
variable "node_desired"       { type = number; default = 2 }
variable "node_min"           { type = number; default = 1 }
variable "node_max"           { type = number; default = 5 }
