apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tenant-b
  namespace: argocd
  labels:
    app: tenant-b
    environment: dev
spec:
  project: default

  source:
    repoURL: https://github.com/Morbid-TRX/k8s-platform.git
    targetRevision: main
    path: tenants/tenant-b

  destination:
    server: https://kubernetes.default.svc
    namespace: tenant-b

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
